#
# Module manifest for module 'dataops'
#
# Generated by: SQL Server Community
#
# Generated on: 2/2/2019
#
@{
    # Version number of this module.
    ModuleVersion     = '1.0.4'

    # ID used to uniquely identify this module
    GUID              = '2729e240-18db-40d3-a162-ad2832a21509'

    # Author of this module
    Author            = 'SQL Server Community'

    # Company or vendor of this module
    CompanyName       = 'SQL Server Community'

    # Copyright statement for this module
    Copyright         = '2019 SQL Server Community'

    # Description of the functionality provided by this module
    Description       = 'Database DevOps meta package: includes dbatools, dbachecks, dbops, and PSDatabaseClone'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules   = @('dbatools', 'dbachecks', 'dbops', 'PSDatabaseClone')

    PrivateData       = @{
        # PSData is module packaging and gallery metadata embedded in PrivateData
        # It's for rebuilding PowerShellGet (and PoshCode) NuGet-style packages
        # We had to do this because it's the only place we're allowed to extend the manifest
        # https://connect.microsoft.com/PowerShell/feedback/details/421837
        PSData = @{
            # The primary categorization of this module (from the TechNet Gallery tech tree).
            Category     = "Database"

            # Keyword tags to help users find this module via navigations and search.
            Tags         = @('database', 'sqlserver', 'datapro', 'devops')

            # The web address of an icon which can be used in galleries to represent this module
            IconUri      = "https://dbatools.io/wp-content/uploads/2019/02/dbabuild.png"

            # Indicates this is a pre-release/testing version of the module.
            IsPrerelease = 'False'
        }
    }
}
