on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
    - id: foo
      uses: potatoqualitee/psmodulecache@v0.0.1
      with:
        modules-to-install: 'PSFramework'
    - run: echo installed-modules-list ${{ steps.foo.outputs.installed-modules }} 
      shell: bash