on: [push]

jobs:
  sample-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set required PowerShell modules
      id: psmodulecache-action-id
      uses: potatoqualitee/psmodulecache@v4
      with:
        modules-to-install: 'PSFramework, Pester, SPReplicator'
    - name: Setup PowerShell module cache
      id: cache-psmodulesupdate
      uses: actions/cache@v2
      with:
          path: |
            /home/runner/.local/share/powershell/Modules/
          key: ${{ runner.os }}-modulesnew
    - name: Install required PowerShell modules
      if: steps.cache-psmodulesupdate.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module ${{ steps.psmodulecache-action-id.outputs.needed }} -ErrorAction Stop
    - name: Show that the Action works
      shell: pwsh
      run: |
          Get-Module PSFramework, Pester, SPrelicator -ListAvailable