name: Cross Platform Import
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Module imports on all platforms
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Display PSModulePath
      shell: pwsh
      run: $Env:PSModulePath
