on: [push]

jobs:
  run-on-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Bump it
      id: pspublish
      uses: potatoqualitee/pspublish@test
      with:
        skipautomatictags: $true
        whatif: $true
        modulepath: ./dataops
        gallerykey: ${{ secrets.GALLERYKEY }}