on:
  push:
    branches:
      - test

jobs:
  make-pic:
    runs-on: ubuntu-latest
    env:
      npm_config_yes: true
      PLAYWRIGHT_BROWSERS_PATH: 0

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: Install nvm
        uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: lts/*

      - name: Install dependencies and run tests
        run: |
          sudo apt-get --assume-yes install libatk1.0-0 libatk-bridge2.0-0 libcups2 libxkbcommon0 libxdamage1 libgbm1 libpango-1.0-0 libcairo2 libatspi2.0-0
          sudo apt --fix-broken install
          sudo npx -y playwright install
          sudo npx -y playwright install-deps
          npx playwright screenshot --viewport-size=1200,630 --color-scheme=dark ./hello.html /mnt/c/temp/hello.png

          echo "<h1>hello</h1>" > /tmp/echo.html
          # npx playwright screenshot --viewport-size=1200,630 --color-scheme=dark /tmp/echo.html /tmp/echo.png
