on:
  push:
    branches:
      - test

jobs:
  make-pic:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install dependencies and run tests
        run: |
          # sudo apt-get --assume-yes install libatk1.0-0 libatk-bridge2.0-0 libcups2 libxkbcommon0 libxdamage1 libgbm1 libpango-1.0-0 libcairo2 libatspi2.0-0
          npx --yes playwright install --with-deps chromium
          echo "<h1>hello</h1>" > /tmp/echo.html
          npx playwright screenshot --viewport-size=1200,630 --color-scheme=dark /tmp/echo.html /tmp/echo.png
