on:
  push:
    branches:
      - test

jobs:
  make-pic:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: nikeee/setup-pandoc@v1
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install playwright and optipng
        run: |
          npx --yes playwright install --with-deps chromium
          sudo apt-get install -y optipng

      - name: Convert files
        shell: pwsh
        run: |
          New-Item -Path /tmp/thumbs -Force -ItemType Directory
          Invoke-WebRequest -Uri https://raw.githubusercontent.com/dataplat/dbatools/master/bin/dbatools-index.json -OutFile /tmp/thumbs/index.json
          $commands = Get-Content -Path /tmp/thumbs/index.json | ConvertFrom-Json
          $template = Get-Content -Path ./template.md

          foreach ($command in $commands) {
            $name = $command.CommandName
            $example = $command.Examples.Split("`n") | Select-Object -First 1 -Skip 1
            $example = $example.Replace("PS C:\>", "")
            $example = $example.Replace("PS>", "")

            $content = $template.Replace("--COMMAND--", $name)
            $content = $content.Replace("--WORKSON--", $command.Availability)
            $content = $content.Replace("--SYNOPSIS--", $command.Synopsis)
            $content = $content.Replace("--EXAMPLE--", $example)
            $content = $content.Replace("--AUTHOR--", $command.Author)

            $content | Set-Content -Path /tmp/thumbs/$name.md
            pandoc -f markdown -t html /tmp/thumbs/$name.md -o /tmp/thumbs/$name.html --self-contained --css=gh-pandoc.css
            npx playwright screenshot --viewport-size=1200,630 /tmp/thumbs/$name.html /tmp/thumbs/$name.png
            optipng -o7 /tmp/thumbs/$name.png | Out-Null
          }

          rm /tmp/thumbs/*.html
          rm /tmp/thumbs/*.md

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: pics
          path: /tmp/thumbs
