on:
  push:
    branches:
      - test

jobs:
  make-pic:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install playwright
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
        run: |
          npx --yes playwright install --with-deps chromium

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: pics
          path: /tmp/echo.png
