name: test a query
on: [push]
defaults:
  run:
    shell: pwsh
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - uses: actions/checkout@v2

      - name: Run the action
        uses: potatoqualitee/mssqlsuite@v1
        with:
          install: sqlengine, sqlpackage

      - name: Install dbatools
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module dbatools

      - name: Encode password from plain text then connect to SQL Server using Invoke-DbaQuery
        run: |
          $password = ConvertTo-SecureString -String dbatools.I0 -AsPlainText -Force
          $cred = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList "sa", $password
          Invoke-DbaQuery -SqlInstance localhost -SqlCredential $cred -Query "SELECT @@VERSION" -Verbose