name: example test
on:
  pull_request:
jobs:
  run-on-linux:
    runs-on: ubuntu-latest
    steps:
      - name: What's installed now
        shell: pwsh
        run: |
          Get-ChildItem -Recurse -Path ~/.local/share/powershell/Modules/ | Select-Object FullName
          Get-ChildItem -Recurse -Path /opt/microsoft/powershell/7/Modules/ | Select-Object FullName
      - uses: actions/cache@v2
        with:
          path: ~/.local/share/powershell/Modules
          key: ${{ runner.os }}-${{ hashFiles('/mymodule.psd1') }}
      - name: Install PowerShell modules
        if: steps.powershell-cache.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module dbatools, benchpress -ErrorAction Stop
      - name: Test installed PowerShell modules
        shell: pwsh
        run: |
          Get-Module -Name dbatools -ListAvailable | Select Path
          Import-Module dbatools -ErrorAction Stop
          Get-Command -Module dbatools | Select -ExpandProperty Name -First 10
      - name: What's installed again
        shell: pwsh
        run: |
          Get-ChildItem -Recurse -Path ~/.local/share/powershell/ | Select-Object FullName
