name: twitter
on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:
defaults:
  run:
    shell: pwsh

jobs:
  blockcheck:
    runs-on: ubuntu-latest
    env:
      BLUEBIRDPS_API_KEY: ${{secrets.TWITTERAPIKEY}}
      BLUEBIRDPS_API_SECRET: ${{secrets.TWITTERAPIKEYSECRET}}
      BLUEBIRDPS_ACCESS_TOKEN: ${{secrets.TWITTERACCESSTOKEN}}
      BLUEBIRDPS_ACCESS_TOKEN_SECRET: ${{secrets.TWITTERACCESSTOKENSECRET}}

    steps:
      - uses: actions/checkout@v2
      - name: 💲 Create variables for module cacher
        id: psmodulecache
        uses: potatoqualitee/psmodulecache@v3
        with:
          modules-to-cache: BlueBirdPS

      - name: 🧰 Run module cacher action
        id: cacher
        uses: actions/cache@v2
        with:
          path: ${{ steps.psmodulecache.outputs.modulepath }}
          key: ${{ steps.psmodulecache.outputs.keygen }}

      - name: 🤩 Install PowerShell modules
        if: steps.cacher.outputs.cache-hit != 'true'
        uses: potatoqualitee/psmodulecache@v3

      - name: 🚀 Run block check
        run: |
          ./twitter/twitter.ps1
