name: twitter
on:
  workflow_dispatch:
defaults:
  run:
    shell: pwsh

jobs:
  blockcheck:
    runs-on: ubuntu-latest
    env:
      TAPIKEY: ${{secrets.TWITTERAPIKEY}}
      TAPIKEYSECRET: ${{secrets.TWITTERAPIKEYSECRET}}
      TACCESSTOKEN: ${{secrets.TWITTERACCESSTOKEN}}
      TACCESSTOKENSECRET: ${{secrets.TWITTERACCESSTOKENSECRET}}
